### ISSUE TITLE
Rename project to `openmedia-arrange` to match original Python project and intent

### ISSUE THREAD

**Issue by groundf** [czech-radio/openmedia-arrange#15]

**Comment by K0F** [comment]
I have no priv. to rename project

**Comment by K0F** [comment]
to taky a navic i vsechny skripty ktery to volaj, prejmenovat lze ale je
nutne byt dusledny a zmenit to opravdu vsude

Dne čt 6. 4. 2023 10:29 uživatel groundf ***@***.***> napsal:

**Comment by K0F** [comment]
ok
